export { default as StudentLogin } from "./StudentLogin/StudentLogin";
export { default as AdminLogin } from "./AdminLogin/AdminLogin";
export { default as Registration } from "./Registration/Registration";
export { default as StudentHome } from "./StudentHome/StudentHome";
export { default as AdminHome } from "./AdminHome/AdminHome";
export { default as LandingPage } from "./LandingPage/LandingPage";
export { default as UserSelect} from "./LandingPage/UserSelectScreen";
export { default as StudentProfile } from "./StudentProfile/StudentProfile";
export { default as GroupHome } from "./GroupHome/GroupHome";
export { default as Groups } from "./Groups/Groups";
export { default as Contact } from "./Contact/Contact";
export { default as StudentRegistration } from "./StudentRegistration/StudentRegistration";
